"""Optional MediaMTX sidecar. Never required for HVX native ALPR or gate control."""

from __future__ import annotations

import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any

from app.config import settings
from app.services.rtsp_probe import redact_url

_process: subprocess.Popen | None = None
_started_at: float = 0.0
_sources: dict[int, dict[str, Any]] = {}
_last_error: str = ""


def mediamtx_bin() -> Path | None:
    env = os.environ.get("SMARTPARK_MEDIAMTX_BIN")
    candidates = []
    if env:
        candidates.append(Path(env))
    repo_vendor = Path(__file__).resolve().parents[2] / "vendor" / "mediamtx"
    candidates.append(repo_vendor / "mediamtx.exe")
    candidates.append(repo_vendor / "mediamtx")
    home = os.environ.get("SMARTPARK_HOME")
    if home:
        candidates.append(Path(home) / "vendor" / "mediamtx" / "mediamtx.exe")
        candidates.append(Path(home) / "vendor" / "mediamtx" / "mediamtx")
    candidates.append(settings.data_dir / "mediamtx" / "mediamtx.exe")
    candidates.append(settings.data_dir / "mediamtx" / "mediamtx")
    which = shutil.which("mediamtx")
    if which:
        candidates.append(Path(which))
    for path in candidates:
        if path.is_file():
            return path
    return None


def config_path() -> Path:
    folder = settings.data_dir / "mediamtx"
    folder.mkdir(parents=True, exist_ok=True)
    return folder / "mediamtx.yml"


def write_config(paths: dict[int, dict[str, Any]] | None = None) -> Path:
    dest = config_path()
    lines = [
        "# Generated by SmartPark. Do not expose these ports off the LAN.",
        "logLevel: warn",
        "rtspAddress: 127.0.0.1:8554",
        "webrtcAddress: 127.0.0.1:8889",
        "hlsAddress: 127.0.0.1:8888",
        "api: yes",
        "apiAddress: 127.0.0.1:9997",
        "paths:",
    ]
    rows = paths if paths is not None else _sources
    if not rows:
        lines.append("  all_others:")
    for camera_id, source in sorted(rows.items()):
        live_uri = str(source.get("uri") or source.get("rtsp_url") or "")
        detect_uri = str(source.get("detect_uri") or live_uri)
        live_name = f"cam{int(camera_id)}"
        detect_name = f"cam{int(camera_id)}_detect"
        for name, uri in ((live_name, live_uri), (detect_name, detect_uri)):
            lines.append(f"  {name}:")
            if uri.startswith("rtsp://"):
                lines.append(f"    source: {uri}")
                lines.append("    sourceOnDemand: no")
                lines.append("    rtspTransport: tcp")
            else:
                lines.append("    source: publisher")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dest


def available() -> bool:
    return mediamtx_bin() is not None


def running() -> bool:
    return _process is not None and _process.poll() is None


def start() -> dict[str, Any]:
    global _process, _started_at, _last_error
    if running():
        return health()
    binary = mediamtx_bin()
    if binary is None:
        _last_error = "MediaMTX binary not installed"
        return health()
    cfg = write_config()
    try:
        _process = subprocess.Popen(
            [str(binary), str(cfg)],
            cwd=str(cfg.parent),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        _started_at = time.monotonic()
        _last_error = ""
    except Exception as exc:
        _last_error = str(exc)[:300]
        _process = None
    return health()


def stop() -> None:
    global _process
    proc = _process
    _process = None
    if proc is None:
        return
    proc.terminate()
    try:
        proc.wait(timeout=3)
    except Exception:
        proc.kill()


def register_source(camera_id: int, source: dict[str, Any]) -> dict[str, Any]:
    _sources[int(camera_id)] = dict(source)
    write_config()
    if running():
        if not reload_paths():
            stop()
            start()
    return live_endpoint(camera_id)


def reload_paths() -> bool:
    """Ask a running MediaMTX to reload path definitions."""
    if not running():
        return False
    import urllib.request

    try:
        req = urllib.request.Request(
            "http://127.0.0.1:9997/v3/config/paths/reload",
            method="POST",
            data=b"",
        )
        with urllib.request.urlopen(req, timeout=2.0) as resp:
            return 200 <= int(resp.status) < 300
    except Exception:
        return False


def unregister_source(camera_id: int) -> None:
    _sources.pop(int(camera_id), None)
    write_config()


def live_endpoint(camera_id: int) -> dict[str, Any]:
    name = f"cam{int(camera_id)}"
    source = _sources.get(int(camera_id)) or {}
    return {
        "camera_id": int(camera_id),
        "kind": "mediamtx",
        "rtsp": f"rtsp://127.0.0.1:8554/{name}",
        "webrtc": f"http://127.0.0.1:8889/{name}",
        "hls": f"http://127.0.0.1:8888/{name}",
        "upstream_redacted": redact_url(str(source.get("uri") or source.get("rtsp_url") or "")),
        "running": running(),
    }


def detect_endpoint(camera_id: int) -> dict[str, Any]:
    body = live_endpoint(camera_id)
    body["kind"] = "mediamtx-detect"
    return body


def health() -> dict[str, Any]:
    return {
        "ok": running(),
        "available": available(),
        "running": running(),
        "binary": str(mediamtx_bin() or ""),
        "sources": sorted(_sources),
        "uptime_seconds": round(time.monotonic() - _started_at, 1) if running() else 0,
        "last_error": _last_error,
        "note": (
            "MediaMTX is optional. HVX native ALPR and LocalMediaGateway stay up if this sidecar is missing."
        ),
    }
