"""Optional MediaMTX sidecar. Never required for HVX native ALPR or gate control."""

from __future__ import annotations

import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any

from app.config import settings
from app.services.rtsp_probe import redact_url

_process: subprocess.Popen | None = None
_started_at: float = 0.0
_sources: dict[int, dict[str, Any]] = {}
_last_error: str = ""
_external_checked_at: float = 0.0
_external_running_cache: bool = False

CONTROL_API = "http://127.0.0.1:9997"
METRICS_ADDRESS = "127.0.0.1:9998"


ROLE_LIVE = "LIVE"
ROLE_DETECT = "DETECT"
ROLE_EVIDENCE = "EVIDENCE"


def live_path_name(camera_id: int) -> str:
    return f"cam{int(camera_id)}"


def detect_path_name(camera_id: int) -> str:
    return f"cam{int(camera_id)}_detect"


def evidence_path_name(camera_id: int) -> str:
    return f"cam{int(camera_id)}_evidence"


def _source_uris(source: dict[str, Any]) -> tuple[str, str, str]:
    live = str(source.get("uri") or source.get("rtsp_url") or "")
    detect = str(source.get("detect_uri") or live)
    evidence = str(source.get("evidence_uri") or source.get("main_uri") or "")
    return live, detect, evidence


def path_plan(camera_id: int, source: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    """One MediaMTX path per *distinct upstream*, tagged with the roles it serves.

    Roles that resolve to the same camera URI share one upstream connection, so
    a camera exposing a single stream is pulled once, not once per role. LIVE and
    DETECT are always-on (software recognition must not stop when nobody views).
    EVIDENCE is pulled on demand because it is only read for explicit snapshots.
    """
    camera_id = int(camera_id)
    row = source if source is not None else (_sources.get(camera_id) or {})
    live, detect, evidence = _source_uris(row)
    transport = str(row.get("transport") or "TCP").lower()
    if transport not in {"tcp", "udp", "auto"}:
        transport = "tcp"
    plan: list[dict[str, Any]] = [
        {"name": live_path_name(camera_id), "uri": live, "roles": [ROLE_LIVE], "on_demand": False, "transport": transport},
    ]
    if detect and detect != live:
        plan.append({"name": detect_path_name(camera_id), "uri": detect, "roles": [ROLE_DETECT], "on_demand": False, "transport": transport})
    else:
        plan[0]["roles"].append(ROLE_DETECT)
    if evidence:
        shared = next((p for p in plan if p["uri"] == evidence), None)
        if shared is not None:
            shared["roles"].append(ROLE_EVIDENCE)
        else:
            plan.append({"name": evidence_path_name(camera_id), "uri": evidence, "roles": [ROLE_EVIDENCE], "on_demand": True, "transport": transport})
    return plan


def path_for_role(camera_id: int, role: str, source: dict[str, Any] | None = None) -> dict[str, Any]:
    wanted = str(role or ROLE_LIVE).upper()
    plan = path_plan(camera_id, source)
    for item in plan:
        if wanted in item["roles"]:
            return item
    return plan[0]


def all_path_names(camera_id: int) -> tuple[str, ...]:
    return (live_path_name(camera_id), detect_path_name(camera_id), evidence_path_name(camera_id))


def mediamtx_bin() -> Path | None:
    env = os.environ.get("SMARTPARK_MEDIAMTX_BIN")
    candidates = []
    if env:
        candidates.append(Path(env))
    repo_vendor = Path(__file__).resolve().parents[2] / "vendor" / "mediamtx"
    candidates.append(repo_vendor / "mediamtx.exe")
    candidates.append(repo_vendor / "mediamtx")
    home = os.environ.get("SMARTPARK_HOME")
    if home:
        candidates.append(Path(home) / "vendor" / "mediamtx" / "mediamtx.exe")
        candidates.append(Path(home) / "vendor" / "mediamtx" / "mediamtx")
    candidates.append(settings.data_dir / "mediamtx" / "mediamtx.exe")
    candidates.append(settings.data_dir / "mediamtx" / "mediamtx")
    which = shutil.which("mediamtx")
    if which:
        candidates.append(Path(which))
    for path in candidates:
        if path.is_file():
            return path
    return None


def config_path() -> Path:
    folder = settings.data_dir / "mediamtx"
    folder.mkdir(parents=True, exist_ok=True)
    return folder / "mediamtx.yml"


def write_config(paths: dict[int, dict[str, Any]] | None = None) -> Path:
    dest = config_path()
    lines = [
        "# Generated by SmartPark. Do not expose these ports off the LAN.",
        "logLevel: warn",
        "rtspAddress: 127.0.0.1:8554",
        # Web browsers run on operator PCs, not necessarily on the Site Server.
        # Keep RTSP local, but expose WHEP signaling + the static ICE/UDP port
        # on the LAN. MediaMTX gathers interface IPs into ICE candidates.
        "webrtcAddress: :8889",
        "webrtcLocalUDPAddress: :8189",
        "webrtcIPsFromInterfaces: yes",
        # v1.11.x uses the singular key. Keep this aligned with the pinned
        # MediaMTX binary in scripts/install_mediamtx.sh.
        "webrtcAllowOrigin: '*'",
        "hlsAddress: 127.0.0.1:8888",
        "api: yes",
        "apiAddress: 127.0.0.1:9997",
        "metrics: yes",
        "metricsAddress: 127.0.0.1:9998",
        "paths:",
    ]
    rows = paths if paths is not None else _sources
    if not rows:
        lines.append("  all_others:")
    for camera_id, source in sorted(rows.items()):
        for item in path_plan(camera_id, source):
            uri = str(item["uri"])
            lines.append(f"  {item['name']}:")
            lines.append(f"    # roles: {', '.join(item['roles'])}")
            if uri.startswith("rtsp://"):
                lines.append(f"    source: {uri}")
                lines.append(f"    sourceOnDemand: {'yes' if item['on_demand'] else 'no'}")
                lines.append(f"    rtspTransport: {item.get('transport') or 'tcp'}")
            else:
                lines.append("    source: publisher")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dest


def available() -> bool:
    return mediamtx_bin() is not None


def _external_running() -> bool:
    """Detect a MediaMTX instance owned by SmartParkMediaService.

    Process-local globals cannot tell the Site Service whether another process
    owns MediaMTX, so probe the local control API with a short cached check.
    """
    global _external_checked_at, _external_running_cache
    now = time.monotonic()
    if now - _external_checked_at < 1.0:
        return _external_running_cache
    _external_checked_at = now
    try:
        import urllib.request
        with urllib.request.urlopen("http://127.0.0.1:9997/v3/config/global/get", timeout=0.25) as resp:
            _external_running_cache = 200 <= int(resp.status) < 300
    except Exception:
        _external_running_cache = False
    return _external_running_cache


def running() -> bool:
    owned = _process is not None and _process.poll() is None
    return owned or _external_running()


def start() -> dict[str, Any]:
    global _process, _started_at, _last_error
    if running():
        return health()
    binary = mediamtx_bin()
    if binary is None:
        _last_error = "MediaMTX binary not installed"
        return health()
    cfg = write_config()
    try:
        _process = subprocess.Popen(
            [str(binary), str(cfg)],
            cwd=str(cfg.parent),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        _started_at = time.monotonic()
        _last_error = ""
    except Exception as exc:
        _last_error = str(exc)[:300]
        _process = None
    return health()


def stop() -> None:
    """Stop only a MediaMTX process started by this Python process."""
    global _process
    proc = _process
    _process = None
    if proc is None:
        return
    proc.terminate()
    try:
        proc.wait(timeout=3)
    except Exception:
        proc.kill()


def _path_conf(uri: str, *, on_demand: bool = False, transport: str = "tcp") -> dict[str, Any]:
    chosen = str(transport or "tcp").lower()
    if chosen not in {"tcp", "udp", "auto"}:
        chosen = "tcp"
    if str(uri).startswith("rtsp://"):
        return {"source": uri, "sourceOnDemand": bool(on_demand), "rtspTransport": chosen}
    return {"source": "publisher"}


def _control_api(method: str, path: str, body: dict[str, Any] | None = None) -> int | None:
    """Call the MediaMTX Control API. None means the API could not be reached."""
    import json
    import urllib.error
    import urllib.request

    data = None if body is None else json.dumps(body).encode("utf-8")
    headers = {"Content-Type": "application/json"} if data is not None else {}
    req = urllib.request.Request(
        f"{CONTROL_API}{path}",
        data=data,
        method=method,
        headers=headers,
    )
    try:
        with urllib.request.urlopen(req, timeout=2.0) as resp:
            return int(resp.status)
    except urllib.error.HTTPError as exc:
        return int(exc.code)
    except Exception:
        return None


def _upsert_path(name: str, uri: str, *, on_demand: bool = False, transport: str = "tcp") -> int | None:
    conf = _path_conf(uri, on_demand=on_demand, transport=transport)
    status = _control_api("POST", f"/v3/config/paths/add/{name}", conf)
    if status == 400:
        status = _control_api("POST", f"/v3/config/paths/replace/{name}", conf)
    return status


def sync_paths() -> bool:
    """Push registered paths through the real Control API.

    ``write_config`` has already updated ``mediamtx.yml``. MediaMTX hot-reloads
    that file, so a missed API call must not restart the process. Only
    SmartParkMediaService starts and stops MediaMTX.
    """
    if not running():
        return False
    ok = True
    for camera_id, source in sorted(_sources.items()):
        planned = path_plan(camera_id, source)
        for item in planned:
            status = _upsert_path(
                item["name"], item["uri"],
                on_demand=item["on_demand"],
                transport=item.get("transport") or "tcp",
            )
            if status is None or status >= 400:
                ok = False
        # Roles that were split earlier but now share an upstream must not leave a
        # stale second pull running against the camera.
        planned_names = {item["name"] for item in planned}
        for name in all_path_names(camera_id):
            if name not in planned_names:
                _control_api("DELETE", f"/v3/config/paths/delete/{name}")
    return ok


def register_source(camera_id: int, source: dict[str, Any]) -> dict[str, Any]:
    camera_id = int(camera_id)
    incoming = dict(source)
    if _sources.get(camera_id) == incoming:
        return live_endpoint(camera_id)
    _sources[camera_id] = incoming
    write_config()
    if running():
        sync_paths()
    return live_endpoint(camera_id)


def reload_paths() -> bool:
    """Apply path changes through add/replace. MediaMTX has no paths reload endpoint."""
    return sync_paths()


def unregister_source(camera_id: int) -> None:
    camera_id = int(camera_id)
    _sources.pop(camera_id, None)
    write_config()
    if running():
        for name in all_path_names(camera_id):
            _control_api("DELETE", f"/v3/config/paths/delete/{name}")


def _endpoint(camera_id: int, role: str, kind: str) -> dict[str, Any]:
    item = path_for_role(camera_id, role)
    name = item["name"]
    return {
        "camera_id": int(camera_id),
        "kind": kind,
        "role": role,
        "mediamtx_path": name,
        "roles": list(item["roles"]),
        "shared_upstream": len(item["roles"]) > 1,
        "on_demand": bool(item["on_demand"]),
        "rtsp": f"rtsp://127.0.0.1:8554/{name}",
        "webrtc": f"http://127.0.0.1:8889/{name}",
        "whep": f"http://127.0.0.1:8889/{name}/whep",
        "hls": f"http://127.0.0.1:8888/{name}",
        "upstream_redacted": redact_url(str(item["uri"] or "")),
        "running": running(),
    }


def live_endpoint(camera_id: int) -> dict[str, Any]:
    return _endpoint(camera_id, ROLE_LIVE, "mediamtx")


def detect_endpoint(camera_id: int) -> dict[str, Any]:
    return _endpoint(camera_id, ROLE_DETECT, "mediamtx-detect")


def evidence_endpoint(camera_id: int) -> dict[str, Any]:
    return _endpoint(camera_id, ROLE_EVIDENCE, "mediamtx-evidence")


def health() -> dict[str, Any]:
    is_running = running()
    paths_summary: dict[str, Any] = {}
    if is_running:
        try:
            from app.services.mediamtx_telemetry import summary as telemetry_summary

            paths_summary = telemetry_summary()
        except Exception as exc:  # telemetry is best-effort; never fail health
            paths_summary = {"error": str(exc)[:200]}
    return {
        "ok": is_running,
        "available": available(),
        "running": is_running,
        "binary": str(mediamtx_bin() or ""),
        "sources": sorted(_sources),
        "paths": [item["name"] for cid in sorted(_sources) for item in path_plan(cid)],
        "control_api": CONTROL_API,
        "telemetry": paths_summary,
        "uptime_seconds": round(time.monotonic() - _started_at, 1) if (_process is not None and _process.poll() is None) else 0,
        "owned_by_this_process": bool(_process is not None and _process.poll() is None),
        "metrics_enabled": True,
        "metrics_address": METRICS_ADDRESS,
        "last_error": _last_error,
        "note": (
            "MediaMTX is optional. HVX native ALPR and LocalMediaGateway stay up if this sidecar is missing."
        ),
    }
